PayRole/Controllers/PayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PayRole.Entity;
using PayRole.Models;
using PayRole.Services;

namespace PayRole.Controllers
{
    public class PayController : Controller
    {
        private readonly IPayRoleService _payRoleService;
        private readonly IEmployeeService _employeeService;
        private readonly ITaxService _taxService;
        private readonly INationalInsuranceContributionService _nationalInsuranceContributionService;
        private decimal overTimeHrs;
        private decimal contractualEarnungs;
        private decimal overTimeEarning;
        private decimal totalEarning;
        private decimal tax;
        private decimal unionFee;
        private decimal studentLoad;
        private decimal nationalInsurance;
        private decimal totalDeduction;

        public PayController(IPayRoleService payRoleService,
            IEmployeeService employeeService,
            ITaxService taxService,
            INationalInsuranceContributionService nationalInsuranceContributionService)
        {
            _payRoleService = payRoleService;
            _employeeService = employeeService;
            _taxService = taxService;
            _nationalInsuranceContributionService = nationalInsuranceContributionService;
        }
        public IActionResult Index()
        {
            var payRecords = _payRoleService.GetAll().Select(pay => new PaymentRecordIndexViewModel
            {
                Id = pay.Id,
                EmployeeId = pay.EmployeeId,
                FullName = pay.FullName,
                PayDate=pay.PayDate,
                PayMonth =pay.PayMonth,
                TaxYearId =pay.TaxYearId,
                Year = _payRoleService.GetTaxYearById(pay.TaxYearId).YearOfTax,
                TotalDeduction = pay.TotalDeductions,
                TotalEarnings =pay.TotalEarnings,
                NetPayment =pay.NetPayment,
                Employee = pay.Employee
            });
            return View(payRecords);
        }

        public IActionResult Create()
        {
            ViewBag.emplyees = _employeeService.GetAllEmployeesForPayroll();
            ViewBag.taxYears = _payRoleService.GetAllTaxYear();
            var model = new PaymentRecordCreateViewModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( PaymentRecordCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var payRecord = new PaymentRecord()
                {
                    Id = model.Id,
                    EmployeeId = model.EmployeeId,
                    FullName = _employeeService.GetById(model.EmployeeId).FullName,
                    Nino = _employeeService.GetById(model.EmployeeId).NationalInsuranceNo,
                    PayDate = model.PayDate,
                    PayMonth = model.PayMonth,
                    TaxYearId = model.TaxYearId,
                    TaxCode = model.TaxCode,
                    HourlyRate = model.HourlyRate,
                    HoursWorked = model.HoursWorked,
                    ContractualHours = model.ContractualHours,
                    OvertimeHours = overTimeHrs = _payRoleService.OvertimeHours(model.HoursWorked, model.ContractualHours),
                    ContractualEarnings = contractualEarnungs = _payRoleService.ContractualEarnings(model.ContractualHours, model.HoursWorked, model.HourlyRate),
                    Overtimearnings = overTimeEarning = _payRoleService.OvertimeEarnings(_payRoleService.OvertimeRate(model.HourlyRate), overTimeHrs),
                    TotalEarnings = totalEarning = _payRoleService.TotalEarnings(overTimeEarning, contractualEarnungs),
                    Tax = tax = _taxService.TaxAmount(totalEarning),
                    UnionFee = unionFee = _employeeService.UnionFees(model.EmployeeId),
                    SLC = studentLoad = _employeeService.StudentLoadRepaymentAmount(model.EmployeeId, totalEarning),
                    NIC = nationalInsurance = _nationalInsuranceContributionService.NIContribution(totalEarning),
                    TotalDeductions = totalDeduction = _payRoleService.TotalDeduction(tax, nationalInsurance, studentLoad, unionFee),
                    NetPayment = _payRoleService.NetPay(totalEarning, totalDeduction)
                };

                await _payRoleService.CreatAsync(payRecord);
                return RedirectToAction(nameof(Index));
            }

            ViewBag.emplyees = _employeeService.GetAllEmployeesForPayroll();
            ViewBag.taxYears = _payRoleService.GetAllTaxYear();
            return View();
        }
    }
}

PayRole/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PayRole</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" />
</head>
<body>

    <div class="container-scroller">
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo"><img src="~/images/Paycompute2.gif" alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                <partial name="_LoginPartial" />
            </div>
        </nav>
        <div class="container-fluid page-body-wrapper">
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="collapse" href="#Employee" aria-expanded="false" aria-controls="ui-basic">
                            <i class="fas fa-users fa-lg text-primary" style="margin-right:0.7em;"></i>
                            <span class="menu-title">Employee</span>
                            <i class="menu-arrow text-primary"></i>
                        </a>

                        <div class="collapse" id="Employee">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item"><a class="nav-link" asp-controller="Employee" asp-action="Create">New Employees</a></li>
                                <li class="nav-item"><a class="nav-link" asp-controller="Employee" asp-action="Index">All Employees</a></li>
                            </ul>
                        </div>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" data-toggle="collapse" href="#PayRoll" aria-expanded="false" aria-controls="ui-basic">
                            <i class="fas fa-pound-sign fa-lg text-primary" style="margin-right:0.7em;"></i>
                            <span class="menu-title">PayRoll</span>
                            <i class="menu-arrow text-primary"></i>
                        </a>

                        <div class="collapse" id="PayRoll">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item"><a class="nav-link" asp-controller="Pay" asp-action="Create">New Pay</a></li>
                                <li class="nav-item"><a class="nav-link" asp-controller="Pay" asp-action="Index">Payment REcords</a></li>
                            </ul>
                        </div>
                    </li>

                </ul>
            </nav>

            <div class="main-panel">
                @*<partial name="_CookieCosentPartial" />*@
                <div class="content-wrapper">
                    @RenderBody()
                </div>
                <footer class="footer">
                    <p>&copy @DateTime.UtcNow.Year - PayRoll - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></p>
                </footer>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>